# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /opt/dna-messenger

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /opt/dna-messenger

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/dna-messenger/CMakeFiles /opt/dna-messenger//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/dna-messenger/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dna_lib

# Build rule for target.
dna_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dna_lib
.PHONY : dna_lib

# fast build rule for target.
dna_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/build
.PHONY : dna_lib/fast

#=============================================================================
# Target rules for targets named cellframe_minimal

# Build rule for target.
cellframe_minimal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cellframe_minimal
.PHONY : cellframe_minimal

# fast build rule for target.
cellframe_minimal/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cellframe_minimal.dir/build.make CMakeFiles/cellframe_minimal.dir/build
.PHONY : cellframe_minimal/fast

#=============================================================================
# Target rules for targets named test_dna_profile

# Build rule for target.
test_dna_profile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_dna_profile
.PHONY : test_dna_profile

# fast build rule for target.
test_dna_profile/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_dna_profile.dir/build.make CMakeFiles/test_dna_profile.dir/build
.PHONY : test_dna_profile/fast

#=============================================================================
# Target rules for targets named test_simple

# Build rule for target.
test_simple: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_simple
.PHONY : test_simple

# fast build rule for target.
test_simple/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple.dir/build.make CMakeFiles/test_simple.dir/build
.PHONY : test_simple/fast

#=============================================================================
# Target rules for targets named kem

# Build rule for target.
kem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 kem
.PHONY : kem

# fast build rule for target.
kem/fast:
	$(MAKE) $(MAKESILENT) -f crypto/kem/CMakeFiles/kem.dir/build.make crypto/kem/CMakeFiles/kem.dir/build
.PHONY : kem/fast

#=============================================================================
# Target rules for targets named dsa

# Build rule for target.
dsa: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dsa
.PHONY : dsa

# fast build rule for target.
dsa/fast:
	$(MAKE) $(MAKESILENT) -f crypto/dsa/CMakeFiles/dsa.dir/build.make crypto/dsa/CMakeFiles/dsa.dir/build
.PHONY : dsa/fast

#=============================================================================
# Target rules for targets named cellframe_dilithium

# Build rule for target.
cellframe_dilithium: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cellframe_dilithium
.PHONY : cellframe_dilithium

# fast build rule for target.
cellframe_dilithium/fast:
	$(MAKE) $(MAKESILENT) -f crypto/cellframe_dilithium/CMakeFiles/cellframe_dilithium.dir/build.make crypto/cellframe_dilithium/CMakeFiles/cellframe_dilithium.dir/build
.PHONY : cellframe_dilithium/fast

#=============================================================================
# Target rules for targets named dht_lib

# Build rule for target.
dht_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dht_lib
.PHONY : dht_lib

# fast build rule for target.
dht_lib/fast:
	$(MAKE) $(MAKESILENT) -f dht/CMakeFiles/dht_lib.dir/build.make dht/CMakeFiles/dht_lib.dir/build
.PHONY : dht_lib/fast

#=============================================================================
# Target rules for targets named persistent_bootstrap

# Build rule for target.
persistent_bootstrap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 persistent_bootstrap
.PHONY : persistent_bootstrap

# fast build rule for target.
persistent_bootstrap/fast:
	$(MAKE) $(MAKESILENT) -f dht/CMakeFiles/persistent_bootstrap.dir/build.make dht/CMakeFiles/persistent_bootstrap.dir/build
.PHONY : persistent_bootstrap/fast

#=============================================================================
# Target rules for targets named quick_lookup

# Build rule for target.
quick_lookup: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 quick_lookup
.PHONY : quick_lookup

# fast build rule for target.
quick_lookup/fast:
	$(MAKE) $(MAKESILENT) -f dht/CMakeFiles/quick_lookup.dir/build.make dht/CMakeFiles/quick_lookup.dir/build
.PHONY : quick_lookup/fast

#=============================================================================
# Target rules for targets named p2p_transport

# Build rule for target.
p2p_transport: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 p2p_transport
.PHONY : p2p_transport

# fast build rule for target.
p2p_transport/fast:
	$(MAKE) $(MAKESILENT) -f p2p/CMakeFiles/p2p_transport.dir/build.make p2p/CMakeFiles/p2p_transport.dir/build
.PHONY : p2p_transport/fast

#=============================================================================
# Target rules for targets named dna_messenger_gui

# Build rule for target.
dna_messenger_gui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dna_messenger_gui
.PHONY : dna_messenger_gui

# fast build rule for target.
dna_messenger_gui/fast:
	$(MAKE) $(MAKESILENT) -f gui/CMakeFiles/dna_messenger_gui.dir/build.make gui/CMakeFiles/dna_messenger_gui.dir/build
.PHONY : dna_messenger_gui/fast

#=============================================================================
# Target rules for targets named dna_messenger_gui_autogen

# Build rule for target.
dna_messenger_gui_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dna_messenger_gui_autogen
.PHONY : dna_messenger_gui_autogen

# fast build rule for target.
dna_messenger_gui_autogen/fast:
	$(MAKE) $(MAKESILENT) -f gui/CMakeFiles/dna_messenger_gui_autogen.dir/build.make gui/CMakeFiles/dna_messenger_gui_autogen.dir/build
.PHONY : dna_messenger_gui_autogen/fast

aes_keywrap.o: aes_keywrap.c.o
.PHONY : aes_keywrap.o

# target to build an object file
aes_keywrap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/aes_keywrap.c.o
.PHONY : aes_keywrap.c.o

aes_keywrap.i: aes_keywrap.c.i
.PHONY : aes_keywrap.i

# target to preprocess a source file
aes_keywrap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/aes_keywrap.c.i
.PHONY : aes_keywrap.c.i

aes_keywrap.s: aes_keywrap.c.s
.PHONY : aes_keywrap.s

# target to generate assembly for a file
aes_keywrap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/aes_keywrap.c.s
.PHONY : aes_keywrap.c.s

armor.o: armor.c.o
.PHONY : armor.o

# target to build an object file
armor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/armor.c.o
.PHONY : armor.c.o

armor.i: armor.c.i
.PHONY : armor.i

# target to preprocess a source file
armor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/armor.c.i
.PHONY : armor.c.i

armor.s: armor.c.s
.PHONY : armor.s

# target to generate assembly for a file
armor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/armor.c.s
.PHONY : armor.c.s

base58.o: base58.c.o
.PHONY : base58.o

# target to build an object file
base58.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cellframe_minimal.dir/build.make CMakeFiles/cellframe_minimal.dir/base58.c.o
.PHONY : base58.c.o

base58.i: base58.c.i
.PHONY : base58.i

# target to preprocess a source file
base58.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cellframe_minimal.dir/build.make CMakeFiles/cellframe_minimal.dir/base58.c.i
.PHONY : base58.c.i

base58.s: base58.c.s
.PHONY : base58.s

# target to generate assembly for a file
base58.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cellframe_minimal.dir/build.make CMakeFiles/cellframe_minimal.dir/base58.c.s
.PHONY : base58.c.s

bip39.o: bip39.c.o
.PHONY : bip39.o

# target to build an object file
bip39.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/bip39.c.o
.PHONY : bip39.c.o

bip39.i: bip39.c.i
.PHONY : bip39.i

# target to preprocess a source file
bip39.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/bip39.c.i
.PHONY : bip39.c.i

bip39.s: bip39.c.s
.PHONY : bip39.s

# target to generate assembly for a file
bip39.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/bip39.c.s
.PHONY : bip39.c.s

bip39_pbkdf2.o: bip39_pbkdf2.c.o
.PHONY : bip39_pbkdf2.o

# target to build an object file
bip39_pbkdf2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/bip39_pbkdf2.c.o
.PHONY : bip39_pbkdf2.c.o

bip39_pbkdf2.i: bip39_pbkdf2.c.i
.PHONY : bip39_pbkdf2.i

# target to preprocess a source file
bip39_pbkdf2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/bip39_pbkdf2.c.i
.PHONY : bip39_pbkdf2.c.i

bip39_pbkdf2.s: bip39_pbkdf2.c.s
.PHONY : bip39_pbkdf2.s

# target to generate assembly for a file
bip39_pbkdf2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/bip39_pbkdf2.c.s
.PHONY : bip39_pbkdf2.c.s

cellframe_json_minimal.o: cellframe_json_minimal.c.o
.PHONY : cellframe_json_minimal.o

# target to build an object file
cellframe_json_minimal.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cellframe_minimal.dir/build.make CMakeFiles/cellframe_minimal.dir/cellframe_json_minimal.c.o
.PHONY : cellframe_json_minimal.c.o

cellframe_json_minimal.i: cellframe_json_minimal.c.i
.PHONY : cellframe_json_minimal.i

# target to preprocess a source file
cellframe_json_minimal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cellframe_minimal.dir/build.make CMakeFiles/cellframe_minimal.dir/cellframe_json_minimal.c.i
.PHONY : cellframe_json_minimal.c.i

cellframe_json_minimal.s: cellframe_json_minimal.c.s
.PHONY : cellframe_json_minimal.s

# target to generate assembly for a file
cellframe_json_minimal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cellframe_minimal.dir/build.make CMakeFiles/cellframe_minimal.dir/cellframe_json_minimal.c.s
.PHONY : cellframe_json_minimal.c.s

cellframe_sign_minimal.o: cellframe_sign_minimal.c.o
.PHONY : cellframe_sign_minimal.o

# target to build an object file
cellframe_sign_minimal.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cellframe_minimal.dir/build.make CMakeFiles/cellframe_minimal.dir/cellframe_sign_minimal.c.o
.PHONY : cellframe_sign_minimal.c.o

cellframe_sign_minimal.i: cellframe_sign_minimal.c.i
.PHONY : cellframe_sign_minimal.i

# target to preprocess a source file
cellframe_sign_minimal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cellframe_minimal.dir/build.make CMakeFiles/cellframe_minimal.dir/cellframe_sign_minimal.c.i
.PHONY : cellframe_sign_minimal.c.i

cellframe_sign_minimal.s: cellframe_sign_minimal.c.s
.PHONY : cellframe_sign_minimal.s

# target to generate assembly for a file
cellframe_sign_minimal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cellframe_minimal.dir/build.make CMakeFiles/cellframe_minimal.dir/cellframe_sign_minimal.c.s
.PHONY : cellframe_sign_minimal.c.s

cellframe_tx_builder_minimal.o: cellframe_tx_builder_minimal.c.o
.PHONY : cellframe_tx_builder_minimal.o

# target to build an object file
cellframe_tx_builder_minimal.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cellframe_minimal.dir/build.make CMakeFiles/cellframe_minimal.dir/cellframe_tx_builder_minimal.c.o
.PHONY : cellframe_tx_builder_minimal.c.o

cellframe_tx_builder_minimal.i: cellframe_tx_builder_minimal.c.i
.PHONY : cellframe_tx_builder_minimal.i

# target to preprocess a source file
cellframe_tx_builder_minimal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cellframe_minimal.dir/build.make CMakeFiles/cellframe_minimal.dir/cellframe_tx_builder_minimal.c.i
.PHONY : cellframe_tx_builder_minimal.c.i

cellframe_tx_builder_minimal.s: cellframe_tx_builder_minimal.c.s
.PHONY : cellframe_tx_builder_minimal.s

# target to generate assembly for a file
cellframe_tx_builder_minimal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cellframe_minimal.dir/build.make CMakeFiles/cellframe_minimal.dir/cellframe_tx_builder_minimal.c.s
.PHONY : cellframe_tx_builder_minimal.c.s

contacts_db.o: contacts_db.c.o
.PHONY : contacts_db.o

# target to build an object file
contacts_db.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/contacts_db.c.o
.PHONY : contacts_db.c.o

contacts_db.i: contacts_db.c.i
.PHONY : contacts_db.i

# target to preprocess a source file
contacts_db.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/contacts_db.c.i
.PHONY : contacts_db.c.i

contacts_db.s: contacts_db.c.s
.PHONY : contacts_db.s

# target to generate assembly for a file
contacts_db.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/contacts_db.c.s
.PHONY : contacts_db.c.s

decrypt.o: decrypt.c.o
.PHONY : decrypt.o

# target to build an object file
decrypt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/decrypt.c.o
.PHONY : decrypt.c.o

decrypt.i: decrypt.c.i
.PHONY : decrypt.i

# target to preprocess a source file
decrypt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/decrypt.c.i
.PHONY : decrypt.c.i

decrypt.s: decrypt.c.s
.PHONY : decrypt.s

# target to generate assembly for a file
decrypt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/decrypt.c.s
.PHONY : decrypt.c.s

dna_api.o: dna_api.c.o
.PHONY : dna_api.o

# target to build an object file
dna_api.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/dna_api.c.o
.PHONY : dna_api.c.o

dna_api.i: dna_api.c.i
.PHONY : dna_api.i

# target to preprocess a source file
dna_api.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/dna_api.c.i
.PHONY : dna_api.c.i

dna_api.s: dna_api.c.s
.PHONY : dna_api.s

# target to generate assembly for a file
dna_api.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/dna_api.c.s
.PHONY : dna_api.c.s

dna_config.o: dna_config.c.o
.PHONY : dna_config.o

# target to build an object file
dna_config.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/dna_config.c.o
.PHONY : dna_config.c.o

dna_config.i: dna_config.c.i
.PHONY : dna_config.i

# target to preprocess a source file
dna_config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/dna_config.c.i
.PHONY : dna_config.c.i

dna_config.s: dna_config.c.s
.PHONY : dna_config.s

# target to generate assembly for a file
dna_config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/dna_config.c.s
.PHONY : dna_config.c.s

encrypt.o: encrypt.c.o
.PHONY : encrypt.o

# target to build an object file
encrypt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/encrypt.c.o
.PHONY : encrypt.c.o

encrypt.i: encrypt.c.i
.PHONY : encrypt.i

# target to preprocess a source file
encrypt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/encrypt.c.i
.PHONY : encrypt.c.i

encrypt.s: encrypt.c.s
.PHONY : encrypt.s

# target to generate assembly for a file
encrypt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/encrypt.c.s
.PHONY : encrypt.c.s

export.o: export.c.o
.PHONY : export.o

# target to build an object file
export.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/export.c.o
.PHONY : export.c.o

export.i: export.c.i
.PHONY : export.i

# target to preprocess a source file
export.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/export.c.i
.PHONY : export.c.i

export.s: export.c.s
.PHONY : export.s

# target to generate assembly for a file
export.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/export.c.s
.PHONY : export.c.s

keygen.o: keygen.c.o
.PHONY : keygen.o

# target to build an object file
keygen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/keygen.c.o
.PHONY : keygen.c.o

keygen.i: keygen.c.i
.PHONY : keygen.i

# target to preprocess a source file
keygen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/keygen.c.i
.PHONY : keygen.c.i

keygen.s: keygen.c.s
.PHONY : keygen.s

# target to generate assembly for a file
keygen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/keygen.c.s
.PHONY : keygen.c.s

keyring.o: keyring.c.o
.PHONY : keyring.o

# target to build an object file
keyring.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/keyring.c.o
.PHONY : keyring.c.o

keyring.i: keyring.c.i
.PHONY : keyring.i

# target to preprocess a source file
keyring.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/keyring.c.i
.PHONY : keyring.c.i

keyring.s: keyring.c.s
.PHONY : keyring.s

# target to generate assembly for a file
keyring.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/keyring.c.s
.PHONY : keyring.c.s

keyserver_cache.o: keyserver_cache.c.o
.PHONY : keyserver_cache.o

# target to build an object file
keyserver_cache.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/keyserver_cache.c.o
.PHONY : keyserver_cache.c.o

keyserver_cache.i: keyserver_cache.c.i
.PHONY : keyserver_cache.i

# target to preprocess a source file
keyserver_cache.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/keyserver_cache.c.i
.PHONY : keyserver_cache.c.i

keyserver_cache.s: keyserver_cache.c.s
.PHONY : keyserver_cache.s

# target to generate assembly for a file
keyserver_cache.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/keyserver_cache.c.s
.PHONY : keyserver_cache.c.s

kyber_deterministic.o: kyber_deterministic.c.o
.PHONY : kyber_deterministic.o

# target to build an object file
kyber_deterministic.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/kyber_deterministic.c.o
.PHONY : kyber_deterministic.c.o

kyber_deterministic.i: kyber_deterministic.c.i
.PHONY : kyber_deterministic.i

# target to preprocess a source file
kyber_deterministic.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/kyber_deterministic.c.i
.PHONY : kyber_deterministic.c.i

kyber_deterministic.s: kyber_deterministic.c.s
.PHONY : kyber_deterministic.s

# target to generate assembly for a file
kyber_deterministic.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/kyber_deterministic.c.s
.PHONY : kyber_deterministic.c.s

message_backup.o: message_backup.c.o
.PHONY : message_backup.o

# target to build an object file
message_backup.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/message_backup.c.o
.PHONY : message_backup.c.o

message_backup.i: message_backup.c.i
.PHONY : message_backup.i

# target to preprocess a source file
message_backup.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/message_backup.c.i
.PHONY : message_backup.c.i

message_backup.s: message_backup.c.s
.PHONY : message_backup.s

# target to generate assembly for a file
message_backup.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/message_backup.c.s
.PHONY : message_backup.c.s

messenger.o: messenger.c.o
.PHONY : messenger.o

# target to build an object file
messenger.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/messenger.c.o
.PHONY : messenger.c.o

messenger.i: messenger.c.i
.PHONY : messenger.i

# target to preprocess a source file
messenger.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/messenger.c.i
.PHONY : messenger.c.i

messenger.s: messenger.c.s
.PHONY : messenger.s

# target to generate assembly for a file
messenger.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/messenger.c.s
.PHONY : messenger.c.s

messenger_p2p.o: messenger_p2p.c.o
.PHONY : messenger_p2p.o

# target to build an object file
messenger_p2p.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/messenger_p2p.c.o
.PHONY : messenger_p2p.c.o

messenger_p2p.i: messenger_p2p.c.i
.PHONY : messenger_p2p.i

# target to preprocess a source file
messenger_p2p.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/messenger_p2p.c.i
.PHONY : messenger_p2p.c.i

messenger_p2p.s: messenger_p2p.c.s
.PHONY : messenger_p2p.s

# target to generate assembly for a file
messenger_p2p.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/messenger_p2p.c.s
.PHONY : messenger_p2p.c.s

messenger_stubs.o: messenger_stubs.c.o
.PHONY : messenger_stubs.o

# target to build an object file
messenger_stubs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/messenger_stubs.c.o
.PHONY : messenger_stubs.c.o

messenger_stubs.i: messenger_stubs.c.i
.PHONY : messenger_stubs.i

# target to preprocess a source file
messenger_stubs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/messenger_stubs.c.i
.PHONY : messenger_stubs.c.i

messenger_stubs.s: messenger_stubs.c.s
.PHONY : messenger_stubs.s

# target to generate assembly for a file
messenger_stubs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/messenger_stubs.c.s
.PHONY : messenger_stubs.c.s

qgp_aes.o: qgp_aes.c.o
.PHONY : qgp_aes.o

# target to build an object file
qgp_aes.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_aes.c.o
.PHONY : qgp_aes.c.o

qgp_aes.i: qgp_aes.c.i
.PHONY : qgp_aes.i

# target to preprocess a source file
qgp_aes.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_aes.c.i
.PHONY : qgp_aes.c.i

qgp_aes.s: qgp_aes.c.s
.PHONY : qgp_aes.s

# target to generate assembly for a file
qgp_aes.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_aes.c.s
.PHONY : qgp_aes.c.s

qgp_dilithium.o: qgp_dilithium.c.o
.PHONY : qgp_dilithium.o

# target to build an object file
qgp_dilithium.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_dilithium.c.o
.PHONY : qgp_dilithium.c.o

qgp_dilithium.i: qgp_dilithium.c.i
.PHONY : qgp_dilithium.i

# target to preprocess a source file
qgp_dilithium.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_dilithium.c.i
.PHONY : qgp_dilithium.c.i

qgp_dilithium.s: qgp_dilithium.c.s
.PHONY : qgp_dilithium.s

# target to generate assembly for a file
qgp_dilithium.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_dilithium.c.s
.PHONY : qgp_dilithium.c.s

qgp_key.o: qgp_key.c.o
.PHONY : qgp_key.o

# target to build an object file
qgp_key.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_key.c.o
.PHONY : qgp_key.c.o

qgp_key.i: qgp_key.c.i
.PHONY : qgp_key.i

# target to preprocess a source file
qgp_key.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_key.c.i
.PHONY : qgp_key.c.i

qgp_key.s: qgp_key.c.s
.PHONY : qgp_key.s

# target to generate assembly for a file
qgp_key.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_key.c.s
.PHONY : qgp_key.c.s

qgp_kyber.o: qgp_kyber.c.o
.PHONY : qgp_kyber.o

# target to build an object file
qgp_kyber.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_kyber.c.o
.PHONY : qgp_kyber.c.o

qgp_kyber.i: qgp_kyber.c.i
.PHONY : qgp_kyber.i

# target to preprocess a source file
qgp_kyber.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_kyber.c.i
.PHONY : qgp_kyber.c.i

qgp_kyber.s: qgp_kyber.c.s
.PHONY : qgp_kyber.s

# target to generate assembly for a file
qgp_kyber.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_kyber.c.s
.PHONY : qgp_kyber.c.s

qgp_platform_linux.o: qgp_platform_linux.c.o
.PHONY : qgp_platform_linux.o

# target to build an object file
qgp_platform_linux.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_platform_linux.c.o
.PHONY : qgp_platform_linux.c.o

qgp_platform_linux.i: qgp_platform_linux.c.i
.PHONY : qgp_platform_linux.i

# target to preprocess a source file
qgp_platform_linux.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_platform_linux.c.i
.PHONY : qgp_platform_linux.c.i

qgp_platform_linux.s: qgp_platform_linux.c.s
.PHONY : qgp_platform_linux.s

# target to generate assembly for a file
qgp_platform_linux.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_platform_linux.c.s
.PHONY : qgp_platform_linux.c.s

qgp_random.o: qgp_random.c.o
.PHONY : qgp_random.o

# target to build an object file
qgp_random.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_random.c.o
.PHONY : qgp_random.c.o

qgp_random.i: qgp_random.c.i
.PHONY : qgp_random.i

# target to preprocess a source file
qgp_random.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_random.c.i
.PHONY : qgp_random.c.i

qgp_random.s: qgp_random.c.s
.PHONY : qgp_random.s

# target to generate assembly for a file
qgp_random.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_random.c.s
.PHONY : qgp_random.c.s

qgp_sha3.o: qgp_sha3.c.o
.PHONY : qgp_sha3.o

# target to build an object file
qgp_sha3.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_sha3.c.o
.PHONY : qgp_sha3.c.o

qgp_sha3.i: qgp_sha3.c.i
.PHONY : qgp_sha3.i

# target to preprocess a source file
qgp_sha3.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_sha3.c.i
.PHONY : qgp_sha3.c.i

qgp_sha3.s: qgp_sha3.c.s
.PHONY : qgp_sha3.s

# target to generate assembly for a file
qgp_sha3.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_sha3.c.s
.PHONY : qgp_sha3.c.s

qgp_signature.o: qgp_signature.c.o
.PHONY : qgp_signature.o

# target to build an object file
qgp_signature.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_signature.c.o
.PHONY : qgp_signature.c.o

qgp_signature.i: qgp_signature.c.i
.PHONY : qgp_signature.i

# target to preprocess a source file
qgp_signature.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_signature.c.i
.PHONY : qgp_signature.c.i

qgp_signature.s: qgp_signature.c.s
.PHONY : qgp_signature.s

# target to generate assembly for a file
qgp_signature.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_signature.c.s
.PHONY : qgp_signature.c.s

qgp_utils_standalone.o: qgp_utils_standalone.c.o
.PHONY : qgp_utils_standalone.o

# target to build an object file
qgp_utils_standalone.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_utils_standalone.c.o
.PHONY : qgp_utils_standalone.c.o

qgp_utils_standalone.i: qgp_utils_standalone.c.i
.PHONY : qgp_utils_standalone.i

# target to preprocess a source file
qgp_utils_standalone.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_utils_standalone.c.i
.PHONY : qgp_utils_standalone.c.i

qgp_utils_standalone.s: qgp_utils_standalone.c.s
.PHONY : qgp_utils_standalone.s

# target to generate assembly for a file
qgp_utils_standalone.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/qgp_utils_standalone.c.s
.PHONY : qgp_utils_standalone.c.s

seed_derivation.o: seed_derivation.c.o
.PHONY : seed_derivation.o

# target to build an object file
seed_derivation.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/seed_derivation.c.o
.PHONY : seed_derivation.c.o

seed_derivation.i: seed_derivation.c.i
.PHONY : seed_derivation.i

# target to preprocess a source file
seed_derivation.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/seed_derivation.c.i
.PHONY : seed_derivation.c.i

seed_derivation.s: seed_derivation.c.s
.PHONY : seed_derivation.s

# target to generate assembly for a file
seed_derivation.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/seed_derivation.c.s
.PHONY : seed_derivation.c.s

sign.o: sign.c.o
.PHONY : sign.o

# target to build an object file
sign.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/sign.c.o
.PHONY : sign.c.o

sign.i: sign.c.i
.PHONY : sign.i

# target to preprocess a source file
sign.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/sign.c.i
.PHONY : sign.c.i

sign.s: sign.c.s
.PHONY : sign.s

# target to generate assembly for a file
sign.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/sign.c.s
.PHONY : sign.c.s

tests/test_dna_profile.o: tests/test_dna_profile.c.o
.PHONY : tests/test_dna_profile.o

# target to build an object file
tests/test_dna_profile.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_dna_profile.dir/build.make CMakeFiles/test_dna_profile.dir/tests/test_dna_profile.c.o
.PHONY : tests/test_dna_profile.c.o

tests/test_dna_profile.i: tests/test_dna_profile.c.i
.PHONY : tests/test_dna_profile.i

# target to preprocess a source file
tests/test_dna_profile.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_dna_profile.dir/build.make CMakeFiles/test_dna_profile.dir/tests/test_dna_profile.c.i
.PHONY : tests/test_dna_profile.c.i

tests/test_dna_profile.s: tests/test_dna_profile.c.s
.PHONY : tests/test_dna_profile.s

# target to generate assembly for a file
tests/test_dna_profile.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_dna_profile.dir/build.make CMakeFiles/test_dna_profile.dir/tests/test_dna_profile.c.s
.PHONY : tests/test_dna_profile.c.s

tests/test_simple.o: tests/test_simple.c.o
.PHONY : tests/test_simple.o

# target to build an object file
tests/test_simple.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple.dir/build.make CMakeFiles/test_simple.dir/tests/test_simple.c.o
.PHONY : tests/test_simple.c.o

tests/test_simple.i: tests/test_simple.c.i
.PHONY : tests/test_simple.i

# target to preprocess a source file
tests/test_simple.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple.dir/build.make CMakeFiles/test_simple.dir/tests/test_simple.c.i
.PHONY : tests/test_simple.c.i

tests/test_simple.s: tests/test_simple.c.s
.PHONY : tests/test_simple.s

# target to generate assembly for a file
tests/test_simple.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_simple.dir/build.make CMakeFiles/test_simple.dir/tests/test_simple.c.s
.PHONY : tests/test_simple.c.s

utils.o: utils.c.o
.PHONY : utils.o

# target to build an object file
utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/utils.c.o
.PHONY : utils.c.o

utils.i: utils.c.i
.PHONY : utils.i

# target to preprocess a source file
utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/utils.c.i
.PHONY : utils.c.i

utils.s: utils.c.s
.PHONY : utils.s

# target to generate assembly for a file
utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/utils.c.s
.PHONY : utils.c.s

verify.o: verify.c.o
.PHONY : verify.o

# target to build an object file
verify.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/verify.c.o
.PHONY : verify.c.o

verify.i: verify.c.i
.PHONY : verify.i

# target to preprocess a source file
verify.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/verify.c.i
.PHONY : verify.c.i

verify.s: verify.c.s
.PHONY : verify.s

# target to generate assembly for a file
verify.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dna_lib.dir/build.make CMakeFiles/dna_lib.dir/verify.c.s
.PHONY : verify.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... dna_messenger_gui_autogen"
	@echo "... cellframe_dilithium"
	@echo "... cellframe_minimal"
	@echo "... dht_lib"
	@echo "... dna_lib"
	@echo "... dna_messenger_gui"
	@echo "... dsa"
	@echo "... kem"
	@echo "... p2p_transport"
	@echo "... persistent_bootstrap"
	@echo "... quick_lookup"
	@echo "... test_dna_profile"
	@echo "... test_simple"
	@echo "... aes_keywrap.o"
	@echo "... aes_keywrap.i"
	@echo "... aes_keywrap.s"
	@echo "... armor.o"
	@echo "... armor.i"
	@echo "... armor.s"
	@echo "... base58.o"
	@echo "... base58.i"
	@echo "... base58.s"
	@echo "... bip39.o"
	@echo "... bip39.i"
	@echo "... bip39.s"
	@echo "... bip39_pbkdf2.o"
	@echo "... bip39_pbkdf2.i"
	@echo "... bip39_pbkdf2.s"
	@echo "... cellframe_json_minimal.o"
	@echo "... cellframe_json_minimal.i"
	@echo "... cellframe_json_minimal.s"
	@echo "... cellframe_sign_minimal.o"
	@echo "... cellframe_sign_minimal.i"
	@echo "... cellframe_sign_minimal.s"
	@echo "... cellframe_tx_builder_minimal.o"
	@echo "... cellframe_tx_builder_minimal.i"
	@echo "... cellframe_tx_builder_minimal.s"
	@echo "... contacts_db.o"
	@echo "... contacts_db.i"
	@echo "... contacts_db.s"
	@echo "... decrypt.o"
	@echo "... decrypt.i"
	@echo "... decrypt.s"
	@echo "... dna_api.o"
	@echo "... dna_api.i"
	@echo "... dna_api.s"
	@echo "... dna_config.o"
	@echo "... dna_config.i"
	@echo "... dna_config.s"
	@echo "... encrypt.o"
	@echo "... encrypt.i"
	@echo "... encrypt.s"
	@echo "... export.o"
	@echo "... export.i"
	@echo "... export.s"
	@echo "... keygen.o"
	@echo "... keygen.i"
	@echo "... keygen.s"
	@echo "... keyring.o"
	@echo "... keyring.i"
	@echo "... keyring.s"
	@echo "... keyserver_cache.o"
	@echo "... keyserver_cache.i"
	@echo "... keyserver_cache.s"
	@echo "... kyber_deterministic.o"
	@echo "... kyber_deterministic.i"
	@echo "... kyber_deterministic.s"
	@echo "... message_backup.o"
	@echo "... message_backup.i"
	@echo "... message_backup.s"
	@echo "... messenger.o"
	@echo "... messenger.i"
	@echo "... messenger.s"
	@echo "... messenger_p2p.o"
	@echo "... messenger_p2p.i"
	@echo "... messenger_p2p.s"
	@echo "... messenger_stubs.o"
	@echo "... messenger_stubs.i"
	@echo "... messenger_stubs.s"
	@echo "... qgp_aes.o"
	@echo "... qgp_aes.i"
	@echo "... qgp_aes.s"
	@echo "... qgp_dilithium.o"
	@echo "... qgp_dilithium.i"
	@echo "... qgp_dilithium.s"
	@echo "... qgp_key.o"
	@echo "... qgp_key.i"
	@echo "... qgp_key.s"
	@echo "... qgp_kyber.o"
	@echo "... qgp_kyber.i"
	@echo "... qgp_kyber.s"
	@echo "... qgp_platform_linux.o"
	@echo "... qgp_platform_linux.i"
	@echo "... qgp_platform_linux.s"
	@echo "... qgp_random.o"
	@echo "... qgp_random.i"
	@echo "... qgp_random.s"
	@echo "... qgp_sha3.o"
	@echo "... qgp_sha3.i"
	@echo "... qgp_sha3.s"
	@echo "... qgp_signature.o"
	@echo "... qgp_signature.i"
	@echo "... qgp_signature.s"
	@echo "... qgp_utils_standalone.o"
	@echo "... qgp_utils_standalone.i"
	@echo "... qgp_utils_standalone.s"
	@echo "... seed_derivation.o"
	@echo "... seed_derivation.i"
	@echo "... seed_derivation.s"
	@echo "... sign.o"
	@echo "... sign.i"
	@echo "... sign.s"
	@echo "... tests/test_dna_profile.o"
	@echo "... tests/test_dna_profile.i"
	@echo "... tests/test_dna_profile.s"
	@echo "... tests/test_simple.o"
	@echo "... tests/test_simple.i"
	@echo "... tests/test_simple.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
	@echo "... verify.o"
	@echo "... verify.i"
	@echo "... verify.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

