# DNA Messenger - Windows Cross-Compilation Builder
# This image contains pre-built MinGW versions of all dependencies
# Build once, use forever in CI for fast Windows builds
#
# Build: docker build -f docker/Dockerfile.windows-builder -t dna-windows-builder .
# Push: docker tag dna-windows-builder yourusername/dna-windows-builder:latest
#       docker push yourusername/dna-windows-builder:latest

FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# Install build tools and MinGW
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    pkg-config \
    wget \
    xxd \
    autoconf \
    automake \
    libtool \
    mingw-w64 \
    g++-mingw-w64-x86-64 \
    gcc-mingw-w64-x86-64 \
    wine \
    wine64 \
    meson \
    ninja-build \
    python3-pip \
    && pip3 install --break-system-packages meson && \
    rm -rf /var/lib/apt/lists/*

# Set up MinGW environment
ENV MINGW_PREFIX=/usr/x86_64-w64-mingw32
ENV PKG_CONFIG_PATH=${MINGW_PREFIX}/lib/pkgconfig
ENV PATH=${MINGW_PREFIX}/bin:$PATH

WORKDIR /build

# Create CMake toolchain file for MinGW (needed before builds)
RUN echo 'set(CMAKE_SYSTEM_NAME Windows)\n\
set(CMAKE_SYSTEM_PROCESSOR x86_64)\n\
set(CMAKE_C_COMPILER x86_64-w64-mingw32-gcc)\n\
set(CMAKE_CXX_COMPILER x86_64-w64-mingw32-g++)\n\
set(CMAKE_RC_COMPILER x86_64-w64-mingw32-windres)\n\
set(CMAKE_FIND_ROOT_PATH /usr/x86_64-w64-mingw32)\n\
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)\n\
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)\n\
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)\n\
set(CMAKE_EXE_LINKER_FLAGS "-static -static-libgcc -static-libstdc++")\n\
set(CMAKE_SHARED_LINKER_FLAGS "-static -static-libgcc -static-libstdc++")\n\
set(WIN32 TRUE)\n\
set(MINGW TRUE)' > /build/mingw-toolchain.cmake

# Create Meson cross-file for GLib/libnice (needed before builds)
RUN echo "[binaries]\n\
c = 'x86_64-w64-mingw32-gcc'\n\
cpp = 'x86_64-w64-mingw32-g++'\n\
ar = 'x86_64-w64-mingw32-ar'\n\
strip = 'x86_64-w64-mingw32-strip'\n\
pkgconfig = 'pkg-config'\n\
\n\
[host_machine]\n\
system = 'windows'\n\
cpu_family = 'x86_64'\n\
cpu = 'x86_64'\n\
endian = 'little'" > /build/mingw-cross.txt

# Build zlib for Windows
RUN wget https://zlib.net/zlib-1.3.1.tar.gz && \
    tar xzf zlib-1.3.1.tar.gz && cd zlib-1.3.1 && \
    CC=x86_64-w64-mingw32-gcc AR=x86_64-w64-mingw32-ar RANLIB=x86_64-w64-mingw32-ranlib \
    ./configure --prefix=${MINGW_PREFIX} --static && \
    make && make install && \
    cd .. && rm -rf zlib-1.3.1*

# Build OpenSSL for Windows
RUN wget https://www.openssl.org/source/openssl-3.0.12.tar.gz && \
    tar xzf openssl-3.0.12.tar.gz && cd openssl-3.0.12 && \
    ./Configure mingw64 --prefix=${MINGW_PREFIX} --cross-compile-prefix=x86_64-w64-mingw32- no-shared && \
    make && make install_sw && \
    cd .. && rm -rf openssl-3.0.12*

# Build libcurl for Windows
RUN wget https://curl.se/download/curl-8.5.0.tar.gz && \
    tar xzf curl-8.5.0.tar.gz && cd curl-8.5.0 && \
    ./configure --host=x86_64-w64-mingw32 --prefix=${MINGW_PREFIX} \
        --with-openssl --enable-static --disable-shared \
        --with-ca-bundle=/etc/ssl/certs/ca-certificates.crt && \
    make && make install && \
    cd .. && rm -rf curl-8.5.0*

# Build json-c for Windows
RUN git clone https://github.com/json-c/json-c.git && cd json-c && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_TOOLCHAIN_FILE=/build/mingw-toolchain.cmake \
        -DCMAKE_INSTALL_PREFIX=${MINGW_PREFIX} \
        -DBUILD_SHARED_LIBS=OFF && \
    make && make install && \
    cd ../.. && rm -rf json-c

# Build SQLite for Windows
RUN wget https://www.sqlite.org/2023/sqlite-autoconf-3440200.tar.gz && \
    tar xzf sqlite-autoconf-3440200.tar.gz && cd sqlite-autoconf-3440200 && \
    ./configure --host=x86_64-w64-mingw32 --prefix=${MINGW_PREFIX} --enable-static --disable-shared && \
    make && make install && \
    cd .. && rm -rf sqlite-autoconf-3440200*

# Build msgpack for Windows
RUN git clone https://github.com/msgpack/msgpack-c.git && cd msgpack-c && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_TOOLCHAIN_FILE=/build/mingw-toolchain.cmake \
        -DCMAKE_INSTALL_PREFIX=${MINGW_PREFIX} \
        -DMSGPACK_BUILD_TESTS=OFF -DMSGPACK_BUILD_EXAMPLES=OFF && \
    make && make install && \
    cd ../.. && rm -rf msgpack-c

# Build GLFW for Windows (ImGui dependency)
RUN git clone https://github.com/glfw/glfw.git && cd glfw && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_TOOLCHAIN_FILE=/build/mingw-toolchain.cmake \
        -DCMAKE_INSTALL_PREFIX=${MINGW_PREFIX} \
        -DBUILD_SHARED_LIBS=OFF -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF && \
    make && make install && \
    cd ../.. && rm -rf glfw

# Build GLEW for Windows
RUN wget https://github.com/nigels-com/glew/releases/download/glew-2.2.0/glew-2.2.0.tgz && \
    tar xzf glew-2.2.0.tgz && cd glew-2.2.0 && \
    cd build/cmake && \
    cmake ./cmake -DCMAKE_TOOLCHAIN_FILE=/build/mingw-toolchain.cmake \
        -DCMAKE_INSTALL_PREFIX=${MINGW_PREFIX} \
        -DBUILD_UTILS=OFF && \
    make && make install && \
    cd ../../.. && rm -rf glew-2.2.0*

# Build FreeType for Windows
RUN wget https://download.savannah.gnu.org/releases/freetype/freetype-2.13.2.tar.gz && \
    tar xzf freetype-2.13.2.tar.gz && cd freetype-2.13.2 && \
    ./configure --host=x86_64-w64-mingw32 --prefix=${MINGW_PREFIX} \
        --enable-static --disable-shared --without-harfbuzz && \
    make && make install && \
    cd .. && rm -rf freetype-2.13.2*

# Build GLib for Windows (required by libnice)
# GLib needs: libffi, pcre2, and libiconv
RUN apt-get update && apt-get install -y gettext && \
    # Build libffi
    wget https://github.com/libffi/libffi/releases/download/v3.4.4/libffi-3.4.4.tar.gz && \
    tar xzf libffi-3.4.4.tar.gz && cd libffi-3.4.4 && \
    ./configure --host=x86_64-w64-mingw32 --prefix=${MINGW_PREFIX} --enable-static --disable-shared && \
    make && make install && \
    cd .. && rm -rf libffi-3.4.4* && \
    # Build pcre2
    wget https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.42/pcre2-10.42.tar.gz && \
    tar xzf pcre2-10.42.tar.gz && cd pcre2-10.42 && \
    ./configure --host=x86_64-w64-mingw32 --prefix=${MINGW_PREFIX} --enable-static --disable-shared && \
    make && make install && \
    cd .. && rm -rf pcre2-10.42* && \
    # Build libiconv
    wget https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.17.tar.gz && \
    tar xzf libiconv-1.17.tar.gz && cd libiconv-1.17 && \
    ./configure --host=x86_64-w64-mingw32 --prefix=${MINGW_PREFIX} --enable-static --disable-shared && \
    make && make install && \
    cd .. && rm -rf libiconv-1.17* && \
    # Build gettext (libintl)
    wget https://ftp.gnu.org/pub/gnu/gettext/gettext-0.22.4.tar.gz && \
    tar xzf gettext-0.22.4.tar.gz && cd gettext-0.22.4 && \
    ./configure --host=x86_64-w64-mingw32 --prefix=${MINGW_PREFIX} --enable-static --disable-shared --disable-java --disable-csharp && \
    make && make install && \
    cd .. && rm -rf gettext-0.22.4*

# Build GLib with Meson
RUN wget https://download.gnome.org/sources/glib/2.78/glib-2.78.3.tar.xz && \
    tar xf glib-2.78.3.tar.xz && cd glib-2.78.3 && \
    meson setup build --cross-file /build/mingw-cross.txt \
        --prefix=${MINGW_PREFIX} \
        --default-library=static \
        -Dtests=false -Dglib_debug=disabled -Dintrospection=disabled && \
    ninja -C build && ninja -C build install && \
    cd .. && rm -rf glib-2.78.3*

# Build GnuTLS for Windows (required by OpenDHT)
RUN apt-get update && apt-get install -y gperf texinfo && \
    # Build nettle (crypto library for GnuTLS)
    wget https://ftp.gnu.org/gnu/nettle/nettle-3.9.1.tar.gz && \
    tar xzf nettle-3.9.1.tar.gz && cd nettle-3.9.1 && \
    ./configure --host=x86_64-w64-mingw32 --prefix=${MINGW_PREFIX} --enable-static --disable-shared --disable-documentation && \
    make && make install && \
    cd .. && rm -rf nettle-3.9.1* && \
    # Build GMP (for nettle/GnuTLS)
    wget https://gmplib.org/download/gmp/gmp-6.3.0.tar.xz && \
    tar xf gmp-6.3.0.tar.xz && cd gmp-6.3.0 && \
    ./configure --host=x86_64-w64-mingw32 --prefix=${MINGW_PREFIX} --enable-static --disable-shared && \
    make && make install && \
    cd .. && rm -rf gmp-6.3.0* && \
    # Build GnuTLS
    wget https://www.gnupg.org/ftp/gcrypt/gnutls/v3.8/gnutls-3.8.2.tar.xz && \
    tar xf gnutls-3.8.2.tar.xz && cd gnutls-3.8.2 && \
    ./configure --host=x86_64-w64-mingw32 --prefix=${MINGW_PREFIX} \
        --enable-static --disable-shared \
        --with-included-libtasn1 --with-included-unistring \
        --without-p11-kit --disable-doc --disable-tests --disable-tools && \
    make && make install && \
    cd .. && rm -rf gnutls-3.8.2*

# Build argon2 for Windows (required by OpenDHT)
RUN git clone https://github.com/P-H-C/phc-winner-argon2.git && cd phc-winner-argon2 && \
    CC=x86_64-w64-mingw32-gcc AR=x86_64-w64-mingw32-ar RANLIB=x86_64-w64-mingw32-ranlib \
    make && \
    mkdir -p ${MINGW_PREFIX}/include ${MINGW_PREFIX}/lib && \
    cp include/argon2.h ${MINGW_PREFIX}/include/ && \
    cp libargon2.a ${MINGW_PREFIX}/lib/ && \
    cd .. && rm -rf phc-winner-argon2

# Build jsoncpp for Windows (required by OpenDHT)
RUN git clone https://github.com/open-source-parsers/jsoncpp.git && cd jsoncpp && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_TOOLCHAIN_FILE=/build/mingw-toolchain.cmake \
        -DCMAKE_INSTALL_PREFIX=${MINGW_PREFIX} \
        -DBUILD_SHARED_LIBS=OFF -DJSONCPP_WITH_TESTS=OFF && \
    make && make install && \
    cd ../.. && rm -rf jsoncpp

# Build libnice for Windows (P2P/ICE)
RUN git clone https://gitlab.freedesktop.org/libnice/libnice.git && cd libnice && \
    meson setup build --cross-file /build/mingw-cross.txt \
        --prefix=${MINGW_PREFIX} \
        --default-library=static \
        -Dtests=disabled -Dexamples=disabled -Dintrospection=disabled \
        -Dgupnp=disabled -Dgstreamer=disabled && \
    ninja -C build && ninja -C build install && \
    cd .. && rm -rf libnice

# Build OpenDHT for Windows (DHT networking)
RUN git clone https://github.com/savoirfairelinux/opendht.git && cd opendht && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_TOOLCHAIN_FILE=/build/mingw-toolchain.cmake \
        -DCMAKE_INSTALL_PREFIX=${MINGW_PREFIX} \
        -DOPENDHT_STATIC=ON -DBUILD_SHARED_LIBS=OFF \
        -DOPENDHT_PYTHON=OFF -DOPENDHT_TOOLS=OFF -DOPENDHT_SYSTEMD=OFF \
        -DOPENDHT_TESTS=OFF -DOPENDHT_DOCUMENTATION=OFF && \
    make && make install && \
    cd ../.. && rm -rf opendht

WORKDIR /workspace

# Set environment for easy building
ENV CMAKE_TOOLCHAIN_FILE=/build/mingw-toolchain.cmake

CMD ["/bin/bash"]
